print("-DEFINITELY NOT A SCAM-")
print()
myName = input("Your Name: ")
print("")
print("Thanks for logging in " + myName)
print("")
cardNumber = input("What is your credit card number?: ")
print("")
print("Thanks " + myName + " I definitely wont put " + cardNumber +  " Into Amazon and order anything weird...")
print("")
print("Promise")
print("")
maidenName = input("What is your Mother's maiden name?: ")
print()
print("That's cool, I just wanted to know that " + maidenName)
print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")
